# Generated by Django 5.0.2 on 2025-05-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_alter_service_options_remove_service_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSectionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Your name for the Hero section.', max_length=100)),
                ('tagline', models.CharField(help_text='Your tagline or short title.', max_length=150)),
                ('description', models.TextField(help_text='The main descriptive text for the Hero section.')),
                ('profile_picture', models.ImageField(help_text='Profile picture for the Hero section.', upload_to='hero_profile_pics/')),
            ],
            options={
                'verbose_name': 'Hero Section Data',
                'verbose_name_plural': 'Hero Section Data',
            },
        ),
    ]
