# Generated by Django 5.2.1 on 2025-05-24 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0008_herosectiondata"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={"ordering": ["order", "-published_date"]},
        ),
        migrations.AlterModelOptions(
            name="experience",
            options={"ordering": ["order", "id"]},
        ),
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["order", "id"]},
        ),
        migrations.AddField(
            model_name="blog",
            name="order",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name="experience",
            name="order",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name="project",
            name="order",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
