# Generated by Django 5.2.1 on 2025-05-24 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0009_alter_blog_options_alter_experience_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="skill",
            name="color",
        ),
        migrations.RemoveField(
            model_name="skill",
            name="level",
        ),
        migrations.AddField(
            model_name="skill",
            name="icon",
            field=models.CharField(
                blank=True,
                help_text='Icon class name (e.g., "fab fa-react")',
                max_length=50,
            ),
        ),
    ]
