# Generated by Django 5.0.2 on 2025-05-22 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_testimonial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['order', 'title']},
        ),
        migrations.AddField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='service',
            name='order',
            field=models.IntegerField(default=0, help_text='Order in which the service should be displayed'),
        ),
        migrations.AddField(
            model_name='service',
            name='tagline',
            field=models.CharField(blank=True, help_text='A short catchy phrase for the service', max_length=200, null=True),
        ),
    ]
